head	1.2;
access;
symbols;
locks; strict;
comment	@# @;


1.2
date	2017.01.06.10.45.20;	author sthen;	state Exp;
branches;
next	1.1;
commitid	CMJjGCJACoHk8ObJ;

1.1
date	2017.01.06.10.33.37;	author sthen;	state Exp;
branches;
next	;
commitid	aox7ZyN6w8W5y28U;


desc
@@


1.2
log
@add further reference to patch comment
@
text
@$OpenBSD: patch-minidb_py,v 1.1 2017/01/06 10:33:37 sthen Exp $

workaround https://bugs.python.org/issue28518
also see https://bugs.python.org/issue10740

--- minidb.py.orig	Fri Jan  6 10:29:50 2017
+++ minidb.py	Fri Jan  6 10:31:03 2017
@@@@ -131,7 +131,7 @@@@ class Store(object):
     MINIDB_ATTR = '_minidb'
 
     def __init__(self, filename=':memory:', debug=False, smartupdate=False):
-        self.db = sqlite3.connect(filename, check_same_thread=False)
+        self.db = sqlite3.connect(filename, check_same_thread=False, isolation_level=None)
         self.debug = debug
         self.smartupdate = smartupdate
         self.registered = {}
@


1.1
log
@Workaround https://bugs.python.org/issue28518 which is breaking urlwatch
following the switch to python 3.6, problem reported by semarie
@
text
@d1 1
a1 1
$OpenBSD$
d4 1
@

